on: [push]
name: Ejecutar tests al hacer un push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar y checkout de la rama actual
        uses: actions/checkout@v1
      - name: Instalar las dependencias
        run: yarn install
      - name: Ejecutando los tests
        run: yarn test
